name: Deploy Azure Functions (publish‑profiles)

on:
  push:
    branches: [main]
    paths:
      - '**/Function/**'
      - '.github/workflows/azure-functions-deploy.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'  # adjust to your LTS

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          #   ── dir (project path) ──          app_name (Azure)            secret key holding publish profile
          - { dir: CreateTimeslotByDate/Function,              app_name: CreateTimeslotsByDate,             publish_profile_secret: PP_CreateTimeslotsByDate }
          - { dir: GetTimeslotsByDate/Function,                app_name: GetTimeslotsByDate,                publish_profile_secret: PP_GetTimeslotsByDate }
          - { dir: UpdateTimeslotsByDate/Function,             app_name: UpdateTimeslotsByDate,             publish_profile_secret: PP_UpdateTimeslotsByDate }
          - { dir: DeleteTimeslotsByDate/Function,             app_name: DeleteTimeslotsByDate,             publish_profile_secret: PP_DeleteTimeslotsByDate }
          - { dir: TriggerTimeslots/Function,                  app_name: TriggerTimeslots,                  publish_profile_secret: PP_TriggerTimeslots }
          - { dir: ConfirmBookingAsync/Function,               app_name: ConfirmBookingAsync,               publish_profile_secret: PP_ConfirmBookingAsync }
          - { dir: GetAllServicesWithSubServices/Function,     app_name: GetAllServicesWithSubServices,     publish_profile_secret: PP_GetAllServicesWithSubServices }
          - { dir: LockAndRelease/Function,                    app_name: LockAndRelease,                    publish_profile_secret: PP_LockAndRelease }

          - { dir: CreateSubService/Function,                  app_name: CreateSubService,                    publish_profile_secret: PP_CreateSubService }
          - { dir: DeleteSubService/Function,                  app_name: DeleteSubService,                    publish_profile_secret: PP_DeleteSubService }
          - { dir: UpdateSubService/Function,                  app_name: UpdateSubService,                    publish_profile_secret: PP_UpdateSubService }
          - { dir: GetSingleSubService/Function,               app_name: GetSingleSubService,               publish_profile_secret: PP_GetSingleSubService }
          - { dir: GetAllSubServices/Function,                 app_name: GetAllSubServices,                  publish_profile_secret: PP_GetAllSubServices }  
          
          - { dir: CreateService/Function,                    app_name: CreateService,                    publish_profile_secret: PP_CreateService }
          - { dir: DeleteService/Function,                    app_name: DeleteService,                    publish_profile_secret: PP_DeleteService }
          - { dir: UpdateService/Function,                    app_name: UpdateService,                    publish_profile_secret: PP_UpdateService }
          - { dir: GetSingleService/Function,                 app_name: GetSingleService,                  publish_profile_secret: PP_GetSingleService }
          - { dir: GetAllServices/Function,                   app_name: GetAllServices,                     publish_profile_secret: PP_GetAllServices }  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build & publish
        working-directory: ${{ matrix.dir }}
        run: |
          dotnet restore
          dotnet publish -c Release -o ../../publish

      - name: Zip‑deploy ${{ matrix.app_name }} using publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.app_name }}
          package: publish
          publish-profile: ${{ secrets[matrix.publish_profile_secret] }}
          sku: flexconsumption
          respect-funcignore: true